### ISSUE TITLE
Installation error due to Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by luizpara** [finnlindgren/fmesher#12]
Hi there.

I am trying to install your library in R with `install.packages("fmesher")` in R 4.2.2, Ubuntu 23.04 64bits, but I am getting an error:

> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** byte-compile and prepare package for lazy loading
> 
>  *** caught segfault ***
> address 0x55b691bcaefd, cause 'memory not mapped'
> An irrecoverable exception occurred. R is aborting now ...
> Segmentation fault (core dumped)
> ERROR: lazy loading failed for package ‘fmesher’

Do you have any idea what may be going on and how to work around that?

**Comment by finnlindgren** [comment]
That looks like some binary incompatibility with the binary package, presumably directly from CRAN? What CRAN mirror do you use? You can try installing from source instead, with `devtools::install_github(“inlabru-org/fmesher”)`. What version of `Rcpp` do you have installed? Some changes in that and related packages recently meant that dependent packages needed to be rebuilt, but since CRAN doesn’t have a mechanism for doing that, it might still have outdated binary builds. I would also recommend upgrading your R installation to the latest version (now 4.3.3).

**Comment by finnlindgren** [comment]
I'm no longer able to build R version 4.2.2 on my system; it seems to want libcurl 7 and I only have libcurl 8 available in the Ubuntu repos, so I can't easily test this issue.
